### ISSUE TITLE
[gatsby] Render issue on back button

### ISSUE THREAD

**Issue by ceiphr** [martinlaxenaire/react-curtains#2]
Hello,

Going back to a previous page containing a react curtains component results in odd render behavior.

Steps to reproduce:
1. Visit: https://www.ceiphr.com/
2. Scroll down and select "A Crash Course in Django"
3. Use the back button to return to the landing page

Result:
![Screenshot_2021-01-06 No-nonsense technical articles from Ari Birnbaum](https://user-images.githubusercontent.com/21004034/103832001-4f694380-504b-11eb-80c5-c265b642cd2d.png)

Expected:
![Screenshot_2021-01-06 No-nonsense technical articles from Ari Birnbaum(1)](https://user-images.githubusercontent.com/21004034/103832140-9b1bed00-504b-11eb-82c4-f91585190cd7.png)

Here is the component I've written:

```js
import React from 'react';
import { Curtains, Plane } from 'react-curtains';

const basicVs = `
    #ifdef GL_ES
    precision mediump float;
    #endif

    // those are the mandatory attributes that the lib sets
    attribute vec3 aVertexPosition;
    attribute vec2 aTextureCoord;

    // those are mandatory uniforms that the lib sets and that contain our model view and projection matrix
    uniform mat4 uMVMatrix;
    uniform mat4 uPMatrix;

    // our texture matrix uniform (this is the lib default name, but it could be changed)
    uniform mat4 uTextureMatrix0;

    // if you want to pass your vertex and texture coords to the fragment shader
    varying vec3 vVertexPosition;
    varying vec2 vTextureCoord;

    void main() {
    // get the vertex position from its attribute
    vec3 vertexPosition = aVertexPosition;
    // set its position based on projection and model view matrix
    gl_Position = uPMatrix * uMVMatrix * vec4(vertexPosition, 1.0);

    // set the varying variables
    // thanks to the texture matrix we will be able to calculate accurate texture coords
    // so that our texture will always fit our plane without being distorted
    vTextureCoord = (uTextureMatrix0 * vec4(aTextureCoord, 0.0, 1.0)).xy;
    vVertexPosition = vertexPosition;
    }
`;


const basicFs = `
    #ifdef GL_ES
    precision mediump float;
    #endif

    // get our varying variables
    varying vec3 vVertexPosition;
    varying vec2 vTextureCoord;

    // the uniform we declared inside our javascript
    uniform float uTime;

    // our texture sampler (this is the lib default name, but it could be changed)
    uniform sampler2D uSampler0;

    void main() {
    // get our texture coords
    vec2 textureCoord = vTextureCoord;

    // displace our pixels along both axis based on our time uniform and texture UVs
    // this will create a kind of water surface effect
    // try to comment a line or change the constants to see how it changes the effect
    // reminder : textures coords are ranging from 0.0 to 1.0 on both axis
    const float PI = 3.141592;

    textureCoord.x += (
        sin(textureCoord.x * 10.0 + ((uTime * (PI / 3.0)) * 0.031))
        + sin(textureCoord.y * 10.0 + ((uTime * (PI / 2.489)) * 0.017))
        ) * 0.0075;

    textureCoord.y += (
        sin(textureCoord.y * 20.0 + ((uTime * (PI / 2.023)) * 0.023))
        + sin(textureCoord.x * 20.0 + ((uTime * (PI / 3.1254)) * 0.037))
        ) * 0.0125;
            
    gl_FragColor = texture2D(uSampler0, textureCoord);
    }
`;

const BasicPlane = ({ children, isfull=false }) => {
    const basicUniforms = {
        time: {
            name: "uTime",
            type: "1f",
            value: 0
        }
    };

    const onRender = (plane) => {
        plane.uniforms.time.value++;
    };

    return (
        <Curtains>
            <Plane
                className= {(isfull ? "FullHeroPlane" : "HeroPlane")}

                // plane init parameters
                vertexShader={basicVs}
                fragmentShader={basicFs}
                uniforms={basicUniforms}
                watchScroll={false}
                antialias={false}
                renderingScale={0.5}

                // plane events
                onRender={onRender}
            >
                {children}
            </Plane>
        </Curtains>
    )
}

export default BasicPlane
```

Related SCSS:

```scss
/* curtains canvas container */

.curtains-canvas {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    width: 120vw;
    canvas {
        transform: scale(1.05);
    }
}

.hero-background__wrapper .curtains-canvas {
    height: 50vh;
}

.hero-fullheight-background__wrapper .curtains-canvas {
    height: 100vh;
}

/* basic plane */

.HeroPlane {
    width: 100vw;
    height: 50vh;
}

.FullHeroPlane {
    width: 100vw;
    height: 100vh;
}

.HeroPlane img,
.FullHeroPlane img {
    display: none;
}
```

I've tested this issue in Chrome Version 87 and Firefox Version 84. The issue is reproducible in both.

Please let me know if any further details are necessary. Thank you for such a great project!
